### ISSUE TITLE
Can't see the location that i entered

### ISSUE THREAD

**Issue by ybrahem** [appoly/ARCore-Location#1]
Hello
i tried building your project but it seems it does not work as i expected, it keeps searching for surfaces and then when i hit in any surface it shows a message saying "Bearing adjustment:" and it does not show any arrows for the location that i entered next to me. i even tried debugging and putting a breakpoint where it should add annotation for the location but it does not enter that particular line which is weird.
Can anybody help ?

**Comment by jguinaud** [comment]
I had the same problem.
Adding `precision mediump float;` to the fragment shader in the annotationRenderer solved the problem for me.

**Comment by DanialKhan777** [comment]
can you please share your code @jguinaud

**Comment by jguinaud** [comment]
I just made a PR with the fix @DanialKhan777 https://github.com/appoly/ARCore-Location/pull/2

**Comment by johnwedgbury** [comment]
Thanks for the fix @jguinaud
