### ISSUE TITLE
Error / Filament : Material version mismatch

### ISSUE THREAD

**Issue by f6qpQNBA3p** [appoly/ARCore-Location#103]
Hello, I got this error :

E/Filament: Panic in filament::Material *filament::Material::Builder::build(filament::Engine &):86
    reason: Material version mismatch. Expected 4 but received 1.

because of this line :
`.setSource(this, R.raw.andy)`

Android Studio 3.5
Emulator Pixel 2 Android 8.1
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 27)
Project using AndroidX, Kotlin

Thanks for the library.

PS: I am not able to open the sfb in Android studio, I got this error :
java.lang.Exception: Bundle version 0,51:1 too old for this executable (max 0,54:1)

Edit: I am able to use the library using a sfb from Poly website, but the distance do not appear, I guess it is because I should use the andy from the library (?)

Please help me

Edit2 : I get a different error using lower versions of arcore/sceneform :
E/Filament: Panic
    in Handle<filament::HwProgram> filament::details::FMaterial::getProgramSlow(uint8_t) const:294
    reason: The material 'FBX Material' has not been compiled to include the required GLSL or SPIR-V chunks for the vertex shader (variant=0xd, filtered=0xd).

**Comment by f6qpQNBA3p** [comment]
https://github.com/appoly/ARCore-Location/issues/87

**Comment by LiZongtai** [comment]
https://developers.google.com/sceneform/develop/create-renderables
