### ISSUE TITLE
How to store current location ?

### ISSUE THREAD

**Issue by xicun9x** [appoly/ARCore-Location#12]
Hi @johnwedgbury ,
I use FusedLocationProviderClient to get CURRENT LOCATION , then I store that position in server and trying to restore it to show in ARCORE. However the position is seem a bit error and show incorrect my CURRENT LOCATION, can you tell me the what the COORDINATE i should to store and how can i get it?

**Comment by johnwedgbury** [comment]
Hi @xicun9x , could you please clarify what you are having an issue with?

Are you having a problem with ARCore-Location, or your own code?
