### ISSUE TITLE
LocationMarker doensn't fix.

### ISSUE THREAD

**Issue by mjy1529** [appoly/ARCore-Location#16]
Hi! I'm a Korean University Student.
We set latitude and logitude like this.

LocationMarker locationMarker = new LocationMarker(37.6559626, 127.06275270000003, getDiaryView());

But while running, the locationmarker is not fixed but move.
What should I do? Please help.

**Comment by johnwedgbury** [comment]
Hi @mjy1529 

The markers are re-calculated every few seconds, and will move a little bit as the calculated direction of north changes.

If this behaviour doesn't suit what you are trying to do, you can change the interval to something greater (such as a minute) with:
locationScene.setAnchorRefreshInterval(60);
