### ISSUE TITLE
Two nodes at the same lat-long start flickering

### ISSUE THREAD

**Issue by ArbabR** [appoly/ARCore-Location#18]
Hi

This library is awesome, thanks for the great work. 

I am having an issue, I have a lot of nodes and some nodes could be at the same lat-long. When two nodes are at the same location, both start to flicker.

**Comment by johnwedgbury** [comment]
Hi @ArbabR 

You could try setting
```
locationScene.setOffsetOverlapping(true);
```

Which will attempt to move one of the markers vertically so they don't overlap. (It needs some work still however, as its not entirely reliable)

Let me know if this doesn't fix your issue, or isn't what you need, and I'll investigate further.

**Comment by ArbabR** [comment]
@johnwedgbury Thanks for the response.

Sure, let me try that.

**Comment by ArbabR** [comment]
Nope, it doesn't work. Please use the same lat-long for multiple nodes to reproduce the issue.

**Comment by ArbabR** [comment]
I have found that blinking is due to the frequent update. It has nothing to do with the same lat-long nodes. 

Closing this issue.
