### ISSUE TITLE
Is there any method in which once renderable is displayed then do not update it in time frame

### ISSUE THREAD

**Issue by basitsaleemmb** [appoly/ARCore-Location#19]
hi! 
update listener in this code updating renderables continuously. I don't want to update them once they created. Need help of you guys.
thanks

**Comment by johnwedgbury** [comment]
Could you refine your question, I'm not too sure what you are asking -

There is no requirement to use ".setRenderEvent". If you don't set it, it won't be called.

The markers are re-calculated every few seconds, and will move a little bit as the calculated direction of north changes.

If this behaviour doesn't suit what you are trying to do, you can change the interval to something greater (such as a minute) with:
locationScene.setAnchorRefreshInterval(60);

**Comment by basitsaleemmb** [comment]
hi @johnwedgbury  
1- My phone is getting very hot due to continuous tracking of camera and location, even i have locationScene.setAnchorRefreshInterval(60);
2- example layout is blinking and also moving with the camera. I think it should be stick to the given lat lng rather than moving.
3- example layout sticks on the camera while moving.
4- camera gets slow after some time and it does not move properly.
