### ISSUE TITLE
Show list location marker with the same layout Renderable ?

### ISSUE THREAD

**Issue by xicun9x** [appoly/ARCore-Location#20]
Hi @johnwedgbury, 
Is there any way to show list location marker with the same layout Renderable ?
and otherwise I use "locationScene.mLocationMarkers.clear();" and then re add it for refresh purpose but it same not workking, can you help me ?

**Comment by johnwedgbury** [comment]
Could you explain in a bit more detail what you are trying to do please?

**Comment by johnwedgbury** [comment]
Here is an example of how you could do that. Some of it is pseudo-code so will require your interpretation.

Have a class for your Coupon Markers:
```
public class CouponMarker extends Marker {

    private static String TAG = "CouponMarker";

    public static void render(Context c, CouponInfo couponInfo, LocationScene locationScene) {

        CompletableFuture<ViewRenderable> couponLayout =
                ViewRenderable.builder()
                        .setView(c, R.layout.coupon_info)
                        .build();


        CompletableFuture.allOf(couponLayout)
                .handle(
                        (notUsed, throwable) -> {

                            if (throwable != null) {
                                Log.i(TAG, "Unable to load renderables");
                                return null;
                            }

                            try {
                                // Non scalable info outside location
                                ViewRenderable vr = couponLayout.get();
                                Node base = new Node();
                                base.setRenderable(vr);
                                TextView title = vr.getView().findViewById(R.id.couponTitle);

                                title.setText( couponInfo.title );


                                LocationMarker couponLocationMarker = new LocationMarker(
                                        couponInfo.longitude,
                                        couponInfo.latitude,
                                        base
                                );

                                couponLocationMarker.setRenderEvent(node -> {
                                    View eView = vr.getView();
                                    TextView distanceTextView = eView.findViewById(R.id.placeDistance);
                                    distanceTextView.setText(Math.round(node.getDistanceInAR()) + "M");
                                });

                                locationScene.mLocationMarkers.add( couponLocationMarker );

                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                            return null;
                        });
    }
}
```

Then when calling your API, do something like so:

```
for(CouponInfo couponInfo: results) {
CouponMarker.render(this, couponInfo, this);
}
```

Let me know if you are still struggling!!

**Comment by xicun9x** [comment]
Hi @johnwedgbury ,
That what i need,
Thanks for your support

**Comment by basitsaleemmb** [comment]
hi @johnwedgbury 
after implement this code camera is moving very slow. Looking for your help!
thanks!

**Comment by drunkenplatypus** [comment]
I've attempted to implement this function above, but with no success. 

I wasn't sure what the `extends Marker` was supposed to do so I created a class called Marker that defines a marker object with the **name**, **lat** and **lon** properties, and then in the MainActivity in the Scene update listener for each frame, I've made a loop that goes through my JSON array, makes a marker object from the rerieved JSON object and then renders it wit the function above.I had to add a default constructor to the class above for it to compile.

The code in my arSceneView scene update listener:
```
if (locationScene == null) {
	// Setup LocationScene object
	locationScene = new LocationScene(this, this, arSceneView);

	for (int n = 0; n < finalNumberOfMarkers; n++) {
		try {
			JSONObject jsonMarker = jsonMarkers.getJSONObject(n);
			RFMarkerRender rfMarker = new RFMarkerRender(
				jsonMarker.getDouble("lon"),
				jsonMarker.getDouble("lat"),
				jsonMarker.getString("name"),
				jsonMarker.getString("type"),
				jsonMarker.getString("mac")
			);
			RFMarkerRender.render(this, rfMarker, locationScene);
		} catch (JSONException e) {
			e.printStackTrace();
		}
	}
}

Frame frame = arSceneView.getArFrame();
if (frame == null) {
	return;
}

if (frame.getCamera().getTrackingState() != TrackingState.TRACKING) {
	return;
}

if (locationScene != null) {
	locationScene.processFrame(frame);
}

if (loadingMessageSnackbar != null) {
	for (Plane plane : frame.getUpdatedTrackables(Plane.class)) {
		if (plane.getTrackingState() == TrackingState.TRACKING) {
			hideLoadingMessage();
		}
	}
}
```
Are you able to give me some help on why I can't see anything rendered? 

Many thanks in advance

**Comment by KushalDesai1** [comment]
Hello.

Is there anyway to add markers at some distance? For e.g., one marker is at a particular point and the other on is at some distance appearing to be small in size.

**Comment by xiangfenr** [comment]
@johnwedgbury     Excuse me, I want to add multiple ViewRenderable, and ViewRenderable does not overlap, and ViewRenderable has 5 states, can we share one Layout?I implemented it according to #34  code, but found it could not be displayed. The following is the code I wrote, please kindly reply to me, thank you
---------------------------------------------This is the marker method---------------
public class DynamicMarker {

    private static String TAG = "CouponMarker";

    public static void render(Context c, DynamicInformation information, LocationScene locationScene) {

        CompletableFuture<ViewRenderable> couponLayout =
                ViewRenderable.builder()
                        .setView(c, R.layout.card)
                        .build();

        CompletableFuture.allOf(couponLayout)
                .handle(
                        (notUsed, throwable) -> {
                            if (throwable != null) {
                                Log.i(TAG, "Unable to load renderables");
                                return null;
                            }
                            try {
                                // Non scalable info outside location
                                ViewRenderable vr = couponLayout.get();
                                Node base = new Node();
                                base.setRenderable(vr);
                                TextView title = vr.getView().findViewById(R.id.tv_message);

                                title.setText(information.getId());

                                double lng = Double.parseDouble(information.getLng());
                                double lat = Double.parseDouble(information.getLat());

                                LocationMarker couponLocationMarker = new LocationMarker(lng, lat, base);

                                couponLocationMarker.setRenderEvent(node -> {
                                    View eView = vr.getView();
                                    TextView distanceTextView = eView.findViewById(R.id.tv_message);
                                    distanceTextView.setText(Math.round(node.getDistanceInAR()) + "M");
                                });
                                locationScene.mLocationMarkers.add(couponLocationMarker);
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                            return null;
                        });
    }

}
----------------This is the method called:-----------------------------
 arSceneView
                .getScene()
                .addOnUpdateListener(
                        frameTime -> {

 for (DynamicInformation information: dynamicInformationList){
                                    DynamicMarker.render(this,information,locationScene);
                                }
}

**Comment by xiangfenr** [comment]
@johnwedgbury  https://github.com/appoly/ARCore-Location/issues/20#issuecomment-396192754  #20  Method doesn't work. There's no marker in my AR

**Comment by xiangfenr** [comment]
@johnwedgbury   Please help me,Please help me  ^_^_ ^_^
