### ISSUE TITLE
Sceneform example crashed after some time

### ISSUE THREAD

**Issue by ArbabR** [appoly/ARCore-Location#22]
I am using Sceneform example, I have placed some nodes on lat-long and start moving the camera around. After playing it for some time the camera gets heavy and finally crashed.

Android Studio: 3.1.1
Device: Samsung Galaxy S7 
Android: 7.0 API level 24

**Comment by johnwedgbury** [comment]
What error did you get as it crashed?

**Comment by ArbabR** [comment]
I have tried to reproduce it but unable to reproduce the crash. But I am confirm that the camera is getting heavier with the passage of time.
