### ISSUE TITLE
Default activity not found.

### ISSUE THREAD

**Issue by HLneoh** [appoly/ARCore-Location#23]
Hi, I did not change any code in the original project folder. However, when I run the code in android studio, it appears "default activity not found". 

Does anyone know why?

**Comment by johnwedgbury** [comment]
Select the main activity "LocationActivity" before running. You may be able to right click on it and run?

**Comment by HLneoh** [comment]
Sorry for the disturbance. 
May I know do I need to create "LocationActivity" by myself?
It is because I cannot find "LocationActivity" in the zip. file.

**Comment by johnwedgbury** [comment]
You should be able to find it at:

ARCore-Location/examples/sceneform/app/src/main/java/uk/co/appoly/sceneform_example/
