### ISSUE TITLE
Not able to add multiple Location Node. Is there any functionality regarding this?

### ISSUE THREAD

**Issue by jagsrajput21** [appoly/ARCore-Location#27]
Hello, I am trying to make an application which shows nearby Point of Interest using ARCore. 
I am able to add a LocationNode in Scene but not able to add more than that. Here is my code-

                     arSceneView
                    .getScene()
                    .setOnUpdateListener(
                        frameTime -> {
                            if (!hasFinishedLoading) {
                                return;
                            }

                            if (locationScene == null) {
                                // If our locationScene object hasn't been setup yet, this is a good time to do it
                                // We know that here, the AR components have been initiated.
                                locationScene = new LocationScene(this, this, arSceneView);
                            }
                                for (Place place : placesList){

                                    LocationMarker layoutLocationMarker = new LocationMarker(
                                            place.getGeometry().getLocation().lat,
                                            place.getGeometry().getLocation().lng,
                                            getAnnotationView()
                                    );

                                    layoutLocationMarker.setRenderEvent(new LocationNodeRender() {
                                        @Override
                                        public void render(LocationNode node) {
                                            View eView = annotationRenderable.getView();
                                            TextView nameTextView = eView.findViewById(R.id.name);
                                            TextView distanceTextView = eView.findViewById(R.id.distance);

                                            nameTextView.setText(place.getName());
                                            distanceTextView.setText(node.getDistance() + "M");
                                        }
                                    });
                                    // Adding the marker
                                    locationScene.mLocationMarkers.add(layoutLocationMarker);
                                    Log.d(TAG, "Added -> "+place.getName());
                                }

                            Frame frame = arSceneView.getArFrame();
                            if (frame == null) {
                                return;
                            }

                            if (frame.getCamera().getTrackingState() != TrackingState.TRACKING) {
                                return;
                            }

                            if (locationScene != null) {
                                locationScene.processFrame(frame);
                            }

                            if (placesList.size()>0){
                                annotationSet = true;
                            }

                        });
                }

Please check if I am doing anything wrong.

**Comment by johnwedgbury** [comment]
Take a look at this:

https://github.com/appoly/ARCore-Location/issues/20
