### ISSUE TITLE
App is getting crashed.

### ISSUE THREAD

**Issue by jagsrajput21** [appoly/ARCore-Location#29]
Sometimes app crashes randomly. 
![screen shot 2018-07-03 at 6 42 56 pm](https://user-images.githubusercontent.com/6915256/42221823-06a8af2e-7ef1-11e8-9d50-0cf1e67e255b.png)

**Comment by johnwedgbury** [comment]
This looks like a Sceneform bug. Please report here instead https://github.com/google-ar/sceneform-android-sdk
