### ISSUE TITLE
Adding 30 nodes make ARsceneview heavy

### ISSUE THREAD

**Issue by ArbabR** [appoly/ARCore-Location#34]
App works great by adding 2 to 4 nodes. I have added 30 to 40 nodes which makes the arsceneview heavy and jerky, although the node consists of simple textview. Looks like heavy calculations and loops are running in the backend. 

Can anyone please guide how to make it smooth?

Thanks

**Comment by johnwedgbury** [comment]
Are you using ViewRenderable? - Unfortunately the way ViewRenderables work in ARCore is pretty resource intensive, so there's a good chance it could be that.

**Comment by ArbabR** [comment]
Yes I am using ViewRenderable. Is there any other way to add nodes which is more efficient? I have followed your suggestion in #20 .

**Comment by Stophface** [comment]
I am interested in a solution to this as well...

**Comment by johnwedgbury** [comment]
Firstly if you must use ViewRenderable, make sure everything is as optimised as possible - all images are compressed and minimal scale etc.

The alternative, if you really want optimal performance, is to create your own renderer directly in OpenGL, and avoid using SceneForm. Here is an example of such a renderer from our legacy version of ARCore-location: https://github.com/appoly/ARCore-Location/blob/legacy/arcore-location/src/main/java/uk/co/appoly/arcorelocation/rendering/AnnotationRenderer.java
