### ISSUE TITLE
Marker added by GPS Coordinates is Unstable.

### ISSUE THREAD

**Issue by ziadagh** [appoly/ARCore-Location#39]
I am using your Sceneform example, only changing the longitude and latitude variables to a location close to me so that I can see it.
However, my issue is that the location does not seem to be stable, I move closer and further from the point or turn around and it keeps on moving. How can I make the marker stay still in place?

**Comment by johnwedgbury** [comment]
If the location marker is within about 100m, it may be that your detected device location isn't accurate enough to get a good bearing.

Have you tried increasing the refresh interval?
`locationScene.setAnchorRefreshInterval(60);`
Alternatively you can tell it to refresh only when it detects a location change from the device:
`locationScene.setRefreshAnchorsAsLocationChanges(true);`

You can also tell the library to stop trying to refine the angles so often with:
`locationScene.setMinimalRefreshing(true);`

**Comment by ziadagh** [comment]
Thank you for the advice, I was able to get a more stable result by adding 
```locationScene.setAnchorRefreshInterval(60);```
