### ISSUE TITLE
Step 3 readme instructions not clear

### ISSUE THREAD

**Issue by mundia416** [appoly/ARCore-Location#45]
in step 3 there is the method on the locationScene  ` processFrame(frame) `, i don't understand where the frame is coming from, where is the frame parameter coming from, i can only find the frametime

``` 
  ....

    if (locationScene != null) {
        locationScene.processFrame(frame);
    }
```

**Comment by johnwedgbury** [comment]
The frame can be recovered like so:

```
Frame frame = arSceneView.getArFrame();
```

**Comment by mundia416** [comment]
oh sweet! thanks... first time using ARCore so pardon my dumb question 😆

**Comment by johnwedgbury** [comment]
Not a problem! The example project may be able to help if you encounter further issues: https://github.com/appoly/ARCore-Location/tree/master/examples/sceneform
