### ISSUE TITLE
Height positioning of elements

### ISSUE THREAD

**Issue by Eliathoran** [appoly/ARCore-Location#46]
I've been searching for changing the height of some of the elements displayed, as they are floating around the area, I found out that when the library sets the position it grabs lat, lng and then the altitude just grabs 0,0. Is this correct? How should I approach then?

**Comment by MuhammadAasharib** [comment]
Hi @Eliathoran have u found any way?

**Comment by johnwedgbury** [comment]
https://github.com/appoly/ARCore-Location/issues/86
