### ISSUE TITLE
mLocationMarkers NullPointerException

### ISSUE THREAD

**Issue by appmaker123** [appoly/ARCore-Location#5]
Hello,

I get:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.ar.core.examples.java.helloar/com.google.ar.core.examples.java.helloar.HelloArActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList uk.co.appoly.arcorelocation.LocationScene.mLocationMarkers' on a null object reference

Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList uk.co.appoly.arcorelocation.LocationScene.mLocationMarkers' on a null object reference

Could you please let me know what I can do to fix this?

Thanks so much!

appmaker123

**Comment by drunkenplatypus** [comment]
I'm having the same error.

Did you manage to fix it?

Thanks
