### ISSUE TITLE
Default Activity Not Found?

### ISSUE THREAD

**Issue by fdheroux** [appoly/ARCore-Location#51]
I tried running the program and it will not even run because it immediately gets this error, "Error running 'app'. Default Activity Not Found". I looked up this error and it says it is typically because there is no "activity" in the manifest files and I noticed that there isn't...I'm not quite sure if this is supposed to happen so I cleaned and rebuilt but it is still getting that error...Any tips?

**Comment by SheikhZayed** [comment]
This is happening because you are opening a wrong project.
The default project contains the ARCore location lib,which you are not interested in ..

If you want to run the example project,copy the contents of example/sceneform and run this as a seperate android project..

it will work..
