### ISSUE TITLE
Cannot inflate ARSceneview

### ISSUE THREAD

**Issue by SheikhZayed** [appoly/ARCore-Location#54]
I get this weird error 

>  android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class com.google.ar.sceneform.ArSceneView

when trying to launch the activity which has sceneview,im starting the project from the scratch using gradle dependency for this lib

although the sceneform example provided here works fine in my device.. ?
any suggestions ?

this is my app.gradle, setting transitive property since i had a conflict with my other lib for com.google.flatbuffers

`implementation ('com.google.ar.sceneform:core:1.5.0') {
        transitive = false
    }
    implementation ('com.google.ar.sceneform.ux:sceneform-ux:1.5.0') {
        transitive = false
    }
    //ARCORE-LOCATION
    implementation('com.github.appoly:ARCore-Location:1.1.1') {
        transitive = false
    }`

**Comment by SheikhZayed** [comment]
fixed the problem,setting the dependency as transitive caused the issue

**Comment by hockAik23** [comment]
Hi Sir, I have same issues, how do you solved this problem? Thank you.
