### ISSUE TITLE
Fix position on orientation change 

### ISSUE THREAD

**Issue by SheikhZayed** [appoly/ARCore-Location#58]
i have noticed that the anchors jumps vigorously when the orientation change occurs,sadly i cannot set the refresh interval to 999999999 as max because i have noticed that sometimes anchors doesnt get displayed at all,

can you suggest some fix for the orientation change behaviour

**Comment by SheikhZayed** [comment]
@Shnafon sorry i didnt get you,could you please eleborate your point

**Comment by Shnafon** [comment]
I mean, it's normal for anchors to jump when there is a change of orientation
the phone's sensors are not 100% reliable
In all the applications I saw using AR with position markers there is this problem
After normal if you stay at a fixed place the marker should not jump vigorously but if you are moving it is quite normal

**Comment by Shnafon** [comment]
sorry I do not really help you

**Comment by SheikhZayed** [comment]
but, you see pokemon go handles it very efficielntly...

i'm using this library on my production app and trying to fix this issue,if done i'll definetly give a PR
meanwhile,you can suggest some info

**Comment by SheikhZayed** [comment]
i was able to get this working,by modifing the code at DeviceOrientation.

i have redesigned the implementation to use the ROTATION_VECTOR  to instead of accelorometer / magnetometer and also using azimuth value to determine the position in x,y,z plane while placing the anchors..not just pitch value

this is giving me very good results without any hack

**Comment by ziadagh** [comment]
Could you supply some code showing how you did that? I too am facing the same problem and losing signal and markers when switching my device's screen orientation.

**Comment by harshadladva** [comment]
can you share your code for orientation problem?? I am facing same problem.
