### ISSUE TITLE
Cannot resolve symbol frame

### ISSUE THREAD

**Issue by jayvardhanc** [appoly/ARCore-Location#59]
In step 3 the line "locationScene.processFrame(frame);" has a frame parameter. Should this be defined as variable. There is no other reference to it.

Note: Since setOnUpdateListener is deprecated I am using addOnUpdateListener.

**Comment by SheikhZayed** [comment]
you can get instance of frame like this 
`Frame frame = arSceneView.getArFrame();`

please close the issue if it resolve your problem
