### ISSUE TITLE
Wrong Positioning

### ISSUE THREAD

**Issue by appmaker123** [appoly/ARCore-Location#6]
I am able to get it to show the location markers, but when I test it with the longitude and latitude of points that are north, south, west and east of me--for example, Milwaukee, Mexico City, Golden Gate Bridge, Statue of Liberty--it would show these four markers on the screen, but in the wrong positions. It would refresh every 5-10 seconds or so, and again the four markers would show up in the wrong positions. For example, it would show Milwaukee south, Mexico City west, Golden Gate Bridge east, etc. Every time it refreshes, the markers would change to a random position and not be where they're supposed to be.

**Comment by johnwedgbury** [comment]
Hi @appmaker123, could you make sure your version in build.grade is 0.0.9 (the latest version) and let me know if you still experience this problem?

I've updated the example code to use the most recent version.

**Comment by appmaker123** [comment]
Hi John, yes, I've made sure to use the build.grade version 0.0.9 but it is still showing the same wrong positions. Could it be because the currentBestLocation is not getting the right coordinates?

**Comment by appmaker123** [comment]
It is working now! Sorry, I was using the wrong lat and long!
