### ISSUE TITLE
Markers are visible for few times only.After while it will automatically invisible or changed their location at random positions.

### ISSUE THREAD

**Issue by Ronakgadhia** [appoly/ARCore-Location#75]
Markers are visible for few times (8-15 seconds) only.After while it will automatically invisible or changed their location at random positions. Can you please give me any solution of this behavior of marker ?

Thanks in advance.

**Comment by thox** [comment]
I am seeing this behaviour as well.

**Comment by johnwedgbury** [comment]
The markers are re-calculated every few seconds, and will move a little bit as the calculated direction of north changes.

If this behaviour doesn't suit what you are trying to do, you can change the interval to something greater (such as 2 minutes) with:
`locationScene.setAnchorRefreshInterval(120);`

**Comment by Ronakgadhia** [comment]
I have increased the time interval but still markers moves automatically and changed their location at random places.

**Comment by MonipichMP** [comment]
I added this line and it worked stable for me.
`locationScene.setRefreshAnchorsAsLocationChanges(true)`
