### ISSUE TITLE
setOnTouchListener

### ISSUE THREAD

**Issue by appmaker123** [appoly/ARCore-Location#8]
Hi John,

How do I set a setOnTouchListener on an annotation? For example. I'd like to be able to touch the Buckingham Palace annotation and have the app do something.

Thanks!
appmaker123

**Comment by johnwedgbury** [comment]
We haven't yet added this feature I'm afraid. It may be added in future - or if anyone wishes to contribute it, it'd be very welcome.

**Comment by appmaker123** [comment]
Okay, thanks!

**Comment by appmaker123** [comment]
Thank you! Checking it out now...
