### ISSUE TITLE
In fragment not working

### ISSUE THREAD

**Issue by pretivj** [appoly/ARCore-Location#84]
Sample example works fine without any issue,when i add the same into fragment it is coming as blank white screen .
What could be the issue,where i am missing?

**Comment by Girrajjangid** [comment]
Failed to resolve: com.github.appoly:ARCore-Location:1.0.6
Can you help me to resolve this? I can't able to download this dependency

**Comment by pretivj** [comment]
Instead of using the API,Download the source code from the same repo and add it in your code itself
