### ISSUE TITLE
How to change height position of elements?

### ISSUE THREAD

**Issue by protoss5482** [appoly/ARCore-Location#86]
Default position ~ center screen. How to move element on the floor?

**Comment by MuhammadAasharib** [comment]
Hi @protoss5482 I am also looking for it. Have u found any way?

**Comment by KirillVolkov** [comment]
me too :((

**Comment by Zhenande** [comment]
I have same question. Is anyone has solution for this question?

**Comment by johnwedgbury** [comment]
https://github.com/appoly/ARCore-Location/blob/master/arcore-location/src/main/java/uk/co/appoly/arcorelocation/LocationMarker.java

LocationMarker has setHeight()
