### ISSUE TITLE
navigation arrows

### ISSUE THREAD

**Issue by mohaz3i** [appoly/ARCore-Location#96]
Hello community,
I'm thinking of adding 3D arrows to help the user navigate to the destination he or she has chosen. Thus, when a user clicks on a marker, the arrows must appear on or in front of the ground and remain pointed at the destination until it is obtained. I have seen similar projects on unity, but I have no idea how to implement this project on android studio and ARcore. Any help is welcome.
Thanks

**Comment by sameerjj** [comment]
check out mapbox, might be a better fit for you

**Comment by mohaz3i** [comment]
yes @sameerjj that's what i was thinking to do and actually even found that it is possible to integrate a unity project in your original android studio project i'm still exploring this path so don't know if it will work or not because i will nedd to pass coordinates of destination and user's. but i was wondering if someone tried before to do it directly on android studio. it would be amazinf add.

**Comment by snibblecorp** [comment]
@mohaz3i I'm actually pursuing a very similar path but haven't actually started. Yea it seems you can sit it in your existing project as an external library, correct? My only concern with this is increase in app size. I actually need to stream and pass messages with OpenTok on top of this which could be a huge challenge - with Unity you can access native Android code but I don't know how much.

**Comment by sameerjj** [comment]
@mohaz3i I'm actually pursuing a very similar path but haven't actually started. Yea it seems you can sit it in your existing project as an external library, correct? My only concern with this is increase in app size. I actually need to stream and pass messages with OpenTok on top of this which could be a huge challenge - with Unity you can access native Android code but I don't know how much.

Let's chat offline and maybe we can exchange notes
