### ISSUE TITLE
Play video with view renderer

### ISSUE THREAD

**Issue by Zhenande** [appoly/ARCore-Location#97]
Hi guys, i got trouble when trying to play video in view. I follow example and can show image, text, ... but it got wrong when show video by VideoView. VideoView can play, but it don't stick with Node of locationMarker. It stick on the center of main layout. Any help is welcome. Thanks

**Comment by johnwedgbury** [comment]
This is a quirk of SceneForm, unrelated to ArCore-Location. VideoView is not supported.

However I'd advise you look at the following example project: https://github.com/google-ar/sceneform-android-sdk/tree/master/samples/chromakeyvideo
